require: rubocop-rails
AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
    - etc/**/*
    - vendor/cache/**/*
    - vendor/bundle/**/*
    - script/rails
    - tmp/**/*
    - '**/*.css'
    - '**/*.scss'
    - '**/*.js'
    - '**/*.html.erb'
    - '**/*.js.erb'
    - '**/*.text.erb'
    - 'app/assets/**/*'
  Include:
    - '**/*.rake'
    - Gemfile
    - Guardfile
    - Rakefile
    - config.ru
    - app/**/*
    - spec/**/*
  TargetRailsVersion: 6.0.3
  TargetRubyVersion: 2.6.3

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 130
  Exclude:
    - '**/*.jbuilder'
    - '**/*.html.erb'
    - 'db/*'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'lib/tasks/*'

Metrics/MethodLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - Brewfile

Style/Lambda:
  EnforcedStyle: literal
