version: 1
 update_configs:
   - package_manager: "ruby:bundler"
     directory: "/"
     update_schedule: "weekly"
     version_requirement_updates: "auto"
     automerged_updates:
       - match:
         dependency_type: "all"
         update_type: "all"
     default_reviewers:
       - "jmkoni"
